### ISSUE TITLE
Change all occurrences of `help_me_out_here` to `help_text`

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#114]
The thing that HMEOH does (editable help) should be compatible with normal help_text definitions.

**Comment by jmurty** [comment]
Can you clarify what should be done for this ticket @cogat? And point me to where `help_me_out_here` has been implemented previously, since I can't see anything that applies this attribute in the current codebase.

**Comment by cogat** [comment]
... I just found a couple of mentions of it and changed them.
