### ISSUE TITLE
Add OG tags content to ListableMixin

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#130]
No new fields, just 3 methods:
* `get_og_title()`. Use `meta_title` attribute if available (it is on `Page` subtypes) and populated, otherwise fall back to `get_title()`
* `get_og_image()`. Just call `get_list_image()`. Define a thumbnailer in `icekit.settings._base` and use it in the template.
* `get_og_description()`.  Use `meta_description` attribute if available (it is on `Page` subtypes) and populated, otherwise fall back to `get_oneliner()`

Then populate the og tags in ACMI's `base.html` with these. No need to worry about the other og tags not covered by these methods.

**Comment by cogat** [comment]
@sam-mi  `get_og_title` should fall back to get_title in the function, not the template. I made the template fix as part of the merge conflict resolution but haven't seen the icekit code yet.

**Comment by sam-mi** [comment]
Sorry @cogat, somehow the abstract_models.py didn't make it into the commit, weird. The `get_og_title` method does fall back to `get_title` however I wasn't sure that every page would include `ACMIListableMixin` so concluded that the base template probably shouldn't assume that either and left it to fall back to `get_title` if `get_og_title` isn't defined on the model.

**Comment by cogat** [comment]
HI Sam

This is an icekit change on the main icekit listablemixin class. The only change in ACMI should be in the template.

**Comment by sam-mi** [comment]
Hey Greg, I've moved the OG tags content to icekit.

**Comment by cogat** [comment]
@sam-mi the OG:Image needs to be an absolute URL
