### ISSUE TITLE
Improve ease of overriding the base template

### ISSUE THREAD

**Issue by markfinger** [ic-labs/django-icekit#16]
It's a bit of a pain to realise that you need to put your app above icekit to override the base template.

I'd prefer this to be more explicit, so I'd suggest a bare `base.html` file in the project's template dir that simply points to `icekit/base.html`, rather than the implicit override in `icekit/templates` that does the same but makes overriding a pain.

I'm happy to implement as a PR, if the suggestion is sane.

Thoughts @mrmachine?

**Comment by mrmachine** [comment]
The project template dir should be first in template dirs setting and installed apps order should not matter. Unless you made an app in the project and put the base template in the app dir. But all app templates should be namespaced to the app anyway. "base.html" has no namespace and doesn't belong in any app. Icekit provides a default but you should add/override for your project in the project templates dir, not an app templates dir. Unless I am misunderstanding something?

**Comment by markfinger** [comment]
Nah, your suggestion sounds reasonable. Sounds like my problems may be down to the project (EDB) using the app style template dir.

Either way, I'll take a poke.

**Comment by markfinger** [comment]
Thanks, @mrmachine. That fixed it.

**Comment by cogat** [comment]
Reopening, because I think this could be documented more clearly in `start.md`

**Comment by cogat** [comment]
@markfinger could you document the approach you took for ACMI in start.md?

**Comment by cogat** [comment]
@markfinger Why is this closed? Where can I see the documentation?

**Comment by markfinger** [comment]
It was closed with the commit above: https://github.com/ic-labs/django-icekit/commit/e4d9ec7e3cb99f2442cca0e346df4623948e34ee
