### ISSUE TITLE
Allow projects to use the ICEkit dev version.

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#18]
Desired outcome: 
- adding VCS link to requirements-local.txt results in the requirement being installed (when?)
- docker uses the requirement in preference to non-vcs link
- src is available in user's local filesystem for edits/commits
- the above is documented in `contributing.md`

Current suggested manual approach from @mrmachine installs the repo but django doesn't pick it up, and it's not in local filesystem.

"To install a dev version, I think just manually `pip install -e git+https://github.com/ic-labs/django-icekit.git#egg=django-icekit` or add an editable VCS link to `requirements-local.txt` (or `requirements.txt` if you want to commit it to your project). I haven't tested. There might be some issues because we expect the `icekit` package to be installed at `/opt/django-icekit/icekit`."

**Comment by mrmachine** [comment]
@cogat I haven't added or updated any docs about running a development version of ICEkit, but I have updated the entrypoint script to detect and use a local editable VCS version of ICEkit (installed into the Python userbase directory when run via Docker).

After installing (either manually or via `requirements-local.txt`, which is installed by `setup-django.sh` during startup), you should exit and restart to re-run entrypoint and detect the editable version and reconfigure the environment.

I'll try to update the docs soon. But in the meantime, it should work when using the `icekit:develop` Docker image (or building a current local image).
