### ISSUE TITLE
Remove map with text?

### ISSUE THREAD

**Issue by markfinger** [ic-labs/django-icekit#182]
Map with text is legacy from another project which needed bespoke maps with a lot of UI treatment. For reasons unknown to me, it has lived on in icekit. If you contrast the two map plugins, you'll see a massive divergence in content entry: the map plugin expects a url to a share map, the map with text expects HTML embed code.

**Comment by markfinger** [comment]
Additionally, neither of these plugins have functional front-ends (outside of a local dev environment) - see: #183

I'd suggest minimising the out-of-the-box map plugins, to reduce maintenance overhead. Map front-ends tend to be fiddly, and Google's Map API tends to break compatibility every couple of years

**Comment by cogat** [comment]
@markfinger which other project uses it? We'll need to move the plugin into there.

**Comment by markfinger** [comment]
SFMOMA or ADC maybe. Can't remember the details unfortunately.

It was definitely one of the earlier projects that either laid the groundwork for icekit or used an early version of it.

**Comment by markfinger** [comment]
Map with text looks like it was copy/pasted from sfmoma: https://github.com/sfmoma/sfmoma/blob/develop/sfmoma/plugins/map/models.py

**Comment by markfinger** [comment]
Given the only project using `MapWithText` has its own vendored code, we can safely remove it from icekit.

**Comment by markfinger** [comment]
Travis is complaining about test failures at present, but I've managed to isolate that the failures are independent of these changes.
