### ISSUE TITLE
Server error response page view needs to pass request context into render template

### ISSUE THREAD

**Issue by bcarberry** [ic-labs/django-icekit#189]
In trying to update SFMOMA's 500.html template to extend the base.html template (in order to maintain site header, nav, footer, and include mixpanel analytics tracking on these error pages), I ran into an error because the SFMOMA base.html expects the request to be passed into the context when rendering the template. This does not currently happen with the server_issue view in Icekit.

**Comment by mrmachine** [comment]
This is a standard Django thing. The 500 error handler does not run context processors (which generally add `request`, among other things) to avoid triggering an exception *while* handling an exception.

The recommended best practice is to ensure that your 500 template *does not* extend from your regular templates and *does not* require any additional context, and does not execute any special template tags (e.g. a tag that fetches content from the database, or a tag that compresses linked CSS/JS).

**Comment by mrmachine** [comment]
Here's some context from a Google Groups discussion a while back:

https://groups.google.com/forum/#!topic/django-developers/UH8ehYL8Pss

The suggestion is that if you need `request` or `user` in your 500 template, you need to write a custom `handler500` view:

https://docs.djangoproject.com/en/1.8/topics/http/views/#customizing-error-views

**Comment by bcarberry** [comment]
Thanks, that does make sense. I'll keep as is.
