### ISSUE TITLE
Add "Can Republish" permission to ICEkit Publishing

### ISSUE THREAD

**Issue by jmurty** [ic-labs/django-icekit#192]
Make it possible to assign users a `can_republish` permission that permits the user to only republish already-published content, and not to publish content for the first time.

This new permission will be distinct from the `can_publish` permission, that allows a user to publish content whether or not it has already been published.

**Comment by jmurty** [comment]
The new `can_republish` user permission is now properly tested and merged to the "develop" branch

**Comment by cogat** [comment]
@jmurty what was the origin of this feature? Who needs to test it?

**Comment by mrmachine** [comment]
@cogat driven by ixc/acmi#311
