### ISSUE TITLE
Next steps docs

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#2]
At the moment, there's not much signposting about where to go after install.

We should add links in index.md to:
* Architectural overview (new?)
* Building a site with GLAMkit (new)
* Creating content
* Creating content plugins
* Contributing

If it's not merged, do this work on https://github.com/ic-labs/django-icekit/tree/feature/project

**Comment by mrmachine** [comment]
Also link to `index.md` from the end of `README.md` and `startproject.sh` as a lead in to the main docs after completing install/setup.

**Comment by cogat** [comment]
I drafted a structural outline:

```- ICEkit docs
	- First steps
		- ICEkit at a glance
		- Quick install guide
			- Detailed install guide
			- Docker
		- Next steps
	- Editors guide
	- Building ICEkit sites
		- Architectural overview
			- Modular content
		- Configuring your site
		- Creating page types
			- Fluent contents
			- Publishing
			- Portable apps
		- Creating content plugins
	- Topic guides
		- Deploying ICEkit
		- Debugging/troubleshooting
	- Advanced topics
		- Page trees and mptt
		- Testing
	- Reference
	- Apps for ICEkit
		- Included apps/pagetypes/plugins
		- 3rd-party
	- Contributing to ICEkit
		- Release notes
		- Standards and collaboration
```

To be DRY, README should be little more than links to docs entry points and places to get more help, much like Django.

@mrmachine OK if I begin restructuring along these lines?

**Comment by mrmachine** [comment]
@cogat I think it's important that the README is actually a bit more than just a link to docs, but definitely a link to full docs should be prominent either near the top or after a brief intro/getting-started section.

From our current README, I would move the "configure your project" and "customise your project" sections to the full docs, but I would keep the rest and add at the top a "What is ICEkit" (or similar) section...

Giving people important information as soon as they land is more important than being completely DRY. We're not Django, and many OSS projects include a decent amount of info the README and also link to full docs on RTD (e.g. fluent as an example).

Besides that, sounds good, but I'd also explicitly link to Changelog as a final section in the TOC/navigation. This is where I look first on any project if I hit a problem that I suspect might be a regression or incompatible change.

**Comment by cogat** [comment]
Refactored docs merged to develop, ready for release.
