### ISSUE TITLE
Add basic support for the IIIF Image API

### ISSUE THREAD

**Issue by jmurty** [ic-labs/django-icekit#204]
The [International Image Interoperability Framework](http://iiif.io) is an emerging standard for managing and serving image assets: "Enabling Richer Access to the World's Images"

To provide a way to generate and return repurposed images – e.g. with cropping or downscaling applied – we will build a basic implementation of the [IIIF Image API 2.1](http://iiif.io/api/image/2.1/) portion of the spec that defines clear and shared URL definitions to do this work.

This is preferable to coming up with our own way to generate and return repurposed images, and could be the basis of longer-term work implementing more of the IIIF standard if that makes sense.

This implementation will be bare bones to start with, offering little more than synchronous (uncached) access for privileged users to repurpose and download image assets.

Further references:
* [Loris image server](https://github.com/loris-imageserver/loris/tree/development/loris) a python implementation of the Image API that we might learn from. Note however that it generates JPG 2000 images and therefore requires a proprietary image library from [Kakadu Software](http://kakadusoftware.com/)
* [blog post](http://www.aaronland.info/weblog/2017/03/05/record/) about a Go IIIF server and useful thoughts on how to manage and expose large image libraries (in short, don't).

**Comment by cogat** [comment]
I think it should be both synchronous (ie not-pregenerated) and cached (once you've generated it, keep it).

**Comment by jmurty** [comment]
To start with we will keep it very simple: 
* a new "iiif" app in ICEkit, optional but included in the GLAMkit config by default
* a privileged view to process URLs that comply with the IIIF Image API
* use easy-thumbails for resizing images, and don't do anything beyond resize/scaling.

**Comment by mrmachine** [comment]
I don't have a lot of the context behind this, but repurposing images in a scalable environment with remote storage (S3) does introduce a few hurdles for us to overcome.

Basically, anything synchronous like easy-thumbnails in its default configuration which generates thumbnails on demand will be ridiculously slow.

With the image being stored on S3, easy-thumbnails has to:

* download the image
* generate a thumbnail
* upload the thumbnail
* return the new URL

Additionally, if for some reason the easy-thumbnails DB does not have up-to-date metadata about which thumbnails it knows has already been generated, it needs to hit the remote storage to check if the file already exists.

The way easy-thumbnails recommends dealing with these issues are:

* Know in advance every type of thumbnail you will need for every category of image. E.g. only generate 32x32 thumbnails for avatars, and only 128x128 for artworks. Simply applying all styles to all images would result in many superfluous thumbnails that never get used (e.g. 128x128 avatars and 32x32 artworks).
* Generate all the required thumbnails at the moment a new image is uploaded, before it is persisted to remote storage and no longer available locally, avoiding the need to block requests while we download/process/upload.
* Store metadata in the database so we can know when a thumbnail already exists and avoid asking the remote file system if we need to generate a thumbnail.

Any new thing we build or 3rd party thing we use to repurpose images will need to deal with these same issues.

**Comment by jmurty** [comment]
NOTE: Developing this on the _204-iiif-image-api_ branch off _feature/image_improvements_ to keep in-sync with ongoing image improvement changes.

**Comment by cogat** [comment]
The current case is going to be a manual on-demand process, so performance isn't a concern yet...

**Comment by jmurty** [comment]
Hi @cogat there should be enough of the IIIF Image API spec implemented now to try it out and give feedback. There is some cleanup and completeness work pending, but the basics are in place.

**Comment by jmurty** [comment]
See https://github.com/ic-labs/django-icekit/pull/206

**Comment by cogat** [comment]
This isn't vital and could be split into a new ticket for the time being, but I couldn't get the region selection http://acmi.lvh.me:8000/iiif/1861/100,150,50,50/50,/0/default.png format to behave as expected. It seems to resize and use the region width/height ratio, but crop from the top/left.

**Comment by cogat** [comment]
Re exposing links in the admin I think for the time being the set up should be on a IIIFConfig model, given a title, and then all the IIIFConfig names (with URLs) would be exposed in the admin for an image. Maybe(?) the slugs of the config names could be used in IIIF urls (instead of `full/` `square/` ?)

**Comment by jmurty** [comment]
@cogat There might be some muddling between the region cropping and size scaling, since currently that all happens in a single image-processing pass. That simple approach is likely _too_ simple, though your description of what is happening matches my understanding of the spec. Definitely should be a separate ticket to hash out the details.

Same with the `IIIFConfig`.
