### ISSUE TITLE
As a bot I can read/write collection items via the API

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#213]
1) Port across the collection configuration from SFMOMA's API
2) Serve API at api.*, using `django-multihost`
3) Allow privileged users to write to the collection records.

This is so that client middleware can write collection records.

**Comment by jmurty** [comment]
The basic APIs for collection items Artwork, Film, Game, Person, and Organization are now all in place and working for at least read operations.

Remaining work is:
* to test writing to the APIs
* unit tests
* whatever is meant by 2. in the ticket description with `django-multihost`

**Comment by jmurty** [comment]
All known work is now done for this feature for now, pending testing with real-world data.

Outstanding work to do once this feature is confirmed working with real data:
* update changelog to document new GLAMkit APIs
* update documentation for GLAMkit APIs, and potentially highlight some of the supporting API utility code that could be reused elsewhere
* make an updated public release of *glamkit-collections* and pin to that version in _setup.py_

**Comment by jmurty** [comment]
This work to bring Collections API support to ICEkit/GLAMkit was merged to the "develop" branch in a467d324
