### ISSUE TITLE
Fix publishing of Fluent Contents items to include related placeholders & content items

### ISSUE THREAD

**Issue by jmurty** [ic-labs/django-icekit#22]
When a Fluent Contents model that is not a Fluent Contents Page is published the related content items `contentitem_set` and `placeholder_set` are not properly cloned to the published copy.

This is because the model-cloning implementation makes some assumptions about how to clone these items, which work for pages but not for non-page models matching the Fluent Contents form, i.e. with `layout`, `contentitem_set`, and `placeholder_set` attributes.

See the related issue AoT 67

**Comment by cogat** [comment]
@jmurty please can you review the docs, specifically

https://github.com/ic-labs/django-icekit/blob/feature/22-fix-publishing-of-fluent-contents/docs/topics/publishing.md#make-custom-publishable-models

and 

https://github.com/ic-labs/django-icekit/blob/feature/22-fix-publishing-of-fluent-contents/docs/howto/page-types.md#abstract-page-type-mixins

for any changes that may result from the rearrangement?

**Comment by jmurty** [comment]
@cogat I have updated the docs, and made some further tweaks to ICEKit so it provides the base classes necessary to easily subclass fluent content models and admins without the need to re-define identical classes in each project.

Providing these base classes results in some breaking changes for downstream projects – now also documented in the changelog – but I think the pain is worth it make working with fluent contents items much cleaner while we still have the chance.
