### ISSUE TITLE
Site map importer

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#236]
At https://docs.google.com/spreadsheets/d/1uOdYPbY655aAYUJCN6-Dq2NZy8Yi06gdV6o62BZ9_CU/edit#gid=0 is a template for site maps. Create an icekit management command to take a csv version of the sitemap, and create LayoutPages that match the shape of the tree, according to the following rules:

- Add a 'Brief' `TextField(blank=True)` to `WorkFlowStateMixin` and expose it in the admin.

- The pages should be unpublished
- If a page exists with the given title at that location in the tree, skip it.
- If a `url_override` value is specified, add that to the `url_override` field.
- ditto `brief`
- Ignore the "Alternative Titles" column.
- make a `--skip-titles-with-brackets` option that skips rows with titles that start and end with either square or round brackets.
- For now, hardcode with 3 levels if it's easier, but anticipate that in future we may need to add more levels.

Finally, add documentation to `/docs` on running the command, referencing the spreadsheet (which is public to anyone with the link), and a link from the spreadsheet to that page in the documentation.

**Comment by cogat** [comment]
* is there a sensible place in the model to log the date/time/source file of the import? If so, do. If not, consider adding an `admin_notes` field to `WorkflowStateMixin`?

**Comment by jmurty** [comment]
Hi @cogat the bulk of the CSV import is working on the _236-site-map-importer_ branch if you are keen to try it. Outstanding work is mentioned in the commit message for ee275175

**Comment by cogat** [comment]
@jmurty All looks good so far! Looking forward to the remaining work.
