### ISSUE TITLE
How to manipulate page tree?

### ISSUE THREAD

**Issue by markfinger** [ic-labs/django-icekit#283]
@cogat it looks like you removed the drag/drop functionality in https://github.com/ic-labs/django-icekit/commit/f0ce0da36fa0cf861a73a8190eaa1ac218beb0bd. What's the alternative for manipulating the page tree?

**Comment by cogat** [comment]
Setting Parent inside the Page admin - it's in a collapsed field... however this doesn't allow to specify ordering.

**Comment by markfinger** [comment]
Thanks!
