### ISSUE TITLE
Fix for latest version of django-polymorphic

### ISSUE THREAD

**Issue by jmurty** [ic-labs/django-icekit#31]
The django-polymorphic library is up to version 1.0.1 and the 1.0 release requires changes to how polymorphic admins need to be registered. Currently ICEKit is not compatible with these changes, resulting in 500 error when you e.g. try to save a page the first time.

Investigate the effort to make ICEKit and required libraries (if necessary) compatible with jango-polymorphic version 1.0+

**Comment by jmurty** [comment]
NOTE: The 500 error only occur when you *Save* a fluent page item, such as ICEKit's `LayoutPage`. If you use the *Save and continue* button it saves correctly and you get no error.

**Comment by jmurty** [comment]
I have created an upstream pull request with our work-around applied directly to the django-polymorphic project in case the fix is useful there. Or it may well be completely misguided, in which case we will get some feedback. https://github.com/django-polymorphic/django-polymorphic/pull/246

**Comment by vdboor** [comment]
A polymorphic 1.0.2 release is out with the fix!

If you guys would like to have more to say in django-fluent, I'd love to share maintainership or other more participating roles! There is a #django-fluent IRC channel and django-fluent slack channel where we can discuss that further!

**Comment by mrmachine** [comment]
@jmurty Can we close this now?

**Comment by cogat** [comment]
ACMI is using polymorphic 1.0.2, so assuming this is closed.
