### ISSUE TITLE
Provide more granular images (commit-based?)

### ISSUE THREAD

**Issue by markfinger** [ic-labs/django-icekit#37]
Some of the projects using icekit have hit major issues because we're dependent on features introduced after the latest tag release, but this dependency on the `develop` image has brought with it breaking changes from the last few days.

We need a way to specify an image from a particular commit or time period, as the the published versions are not granular enough during this initial dev period where backwards compatibility is being broken on a weekly basis.

One alternative is to more frequently publish versions.

**Comment by markfinger** [comment]
As a work around, I'm having to create a branch that the CI will create an image for.

**Comment by mrmachine** [comment]
@markfinger Thanks for making an issue for this so it doesn't get lost. My tentative plan is to see if we can make CI tag Docker images with the Git commit hash as well as the branch/tag. This will make it possible (trivial) to do `FROM interaction/icekit:{SHA}` in a project's `Dockerfile` to use any non-release version of ICEkit without having to unpin.

However, I think that `docker push` might not be smart enough to recognise that the image layers for one tag (git branch/tag) are actually the same as another (git commit hash) and skip the upload step. I'll need to confirm that.

Event if it is the case, it might still be worth doing for ICEkit. If it's not the case, it might be worth doing for all projects that produce Docker images.

**Comment by mrmachine** [comment]
@markfinger It seems to add only a few seconds to do a second push with a different tag (commit hash), so that's what we are doing now in `.travis.yml` for ICEkit itself and in the project template. We should now be able to pin a project to use any intermediate version of ICEkit (and all its dependencies, baked into the ICEkit image) by referencing its commit has in the project `Dockerfile`:

    FROM interaction/icekit:e9a5cbf1247926f43cf41d68e271b99facb99c83

**Comment by mrmachine** [comment]
Fixed in eb11c1ed41327b002e593decaada5b9dd6edb9be
