### ISSUE TITLE
Ensure that sentry handles celery task failures

### ISSUE THREAD

**Issue by markfinger** [ic-labs/django-icekit#38]
I've added the following code into the `tasks.py` file in a project so that celery task failures are being picked up and reported correctly.

```python
from raven.contrib.django.raven_compat.models import client
from raven.contrib.celery import register_signal, register_logger_signal

# Sentry/raven integration for celery - https://docs.sentry.io/clients/python/integrations/celery/
# Register a custom filter to filter out duplicate logs
register_logger_signal(client)
# Hook into the Celery error handler
register_signal(client)
```

cc @mrmachine

**Comment by markfinger** [comment]
I placed it in the `tasks.py` file as it's loaded when celery beat starts triggers recurring events. Not sure what the best place for other projects would be.

**Comment by mrmachine** [comment]
@markfinger Can we put it in `icekit/project/celery.py`? this is where the icekit celery app is defined (which may discover tasks in any installed app).

**Comment by markfinger** [comment]
Yeah, should be good. That sounds like the spot that the sentry/raven docs suggest.

**Comment by markfinger** [comment]
Fixed on `develop` branch
