### ISSUE TITLE
Add an integration point for project URLs.

### ISSUE THREAD

**Issue by mrmachine** [ic-labs/django-icekit#40]
I imagine this looks something like:

``` python
# icekit/project/urls.py
try:
    from project_urls import urlpatterns as project_urlpatterns
except ImportError:
    project_urlpatterns = ()

urlpatterns = patterns(
    '',
    include(r'^', project_urlpatterns),
    ...
)
```

We would need to be careful about projects providing a catch-all URL, which would not only override the ICEkit catch-all URL (fluent dispatcher), but all ICEkit URLs.

**Comment by cogat** [comment]
This is fixed - projects can provide their own URLs by specifying in `project_settings`.
