### ISSUE TITLE
Fix soundcloud embed

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#46]
Seems to be a bug where it tries to write `100%` into an integer field. see ACMI sentry https://sentry.ixcsandbox.com/ic/acmi-stg/group/5579/

**Comment by cogat** [comment]
https://github.com/django-fluent/django-fluent-contents/issues/65

**Comment by sam-mi** [comment]
Hey Greg, I've reporposed the sfmoma solution to this in icekit

**Comment by luciepaterson** [comment]
@timjmansfield please move this into Done. I don't have permissions for icekit.
