### ISSUE TITLE
Alter the nav model

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#48]
We need a superuser-editable menu. After discussion with SFMOMA, we think:

Create a `fluent-contents` model called `Navigation`, having `name`, `slug`, `pre_html`, `post_html` fields. The `_html` ones can just be textfields, no fancy editor. `pre_` and `post_html` default to `<nav><ul>` and `</nav></ul>`

Inside each `Navigation` instance, you can add as many content plugins as you like. The existing `RawHtml` plugin can be added here and new `NavigationItem` and `AccountsNavigationItem` plugin.

The `NavigationItem` has `title = CharField`, `url = ICEkitURLField`. In a collapsed "Advanced" fieldset, add fields for css class and any ARIA/analytics fields that are used on e.g. the SFMOMA menus.

(There is a challenge which is how to decide whether a navigation item should be rendered as `selected`. I'm interested in ideas here. Do we compare the `URL` with a regex defined in a RegexField? Do we provide middleware that sets a value in the context?)

The `AccountsNavigationItem` item renders a project-specific dynamic log in/out menu, a hardcoded template for now.

When the `Navigation` is rendered, a template is rendered, which renders pre-html, post-html and the html for all the content items. The template receives the context of the containing page in the {{ page }}

From https://app.assembla.com/spaces/icekit/simple_planner#/ticket:87

**Comment by markfinger** [comment]
Merged #256 into `develop`
