### ISSUE TITLE
Make preview links use ?preview not ?edit

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#85]
?edit is misleading. Is this a fluent thing?

**Comment by jmurty** [comment]
The `?edit` GET parameter name was our choice for some reason deep in history, but is indeed misleading. Fluent is not involved at all. Changing this to `?preview` instead should be a pretty quick fix touching only code in ICEKit's publishing module. Though if we want to continue supporting the old `?edit` links it might get more complicated.

**Comment by cogat** [comment]
Maybe `edit` could continue to work for the time being...?

**Comment by jmurty** [comment]
Awaiting review and merge in pr #239
