### ISSUE TITLE
Documentation: testing

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#9]
Not sure what we need to say about testing? At least we should include running tests without migrations in `commands.py`

**Comment by mrmachine** [comment]
In `contributing.md` we say:

```
We don't strictly need 100% test coverage, but we aim to have:

  * Unit tests for all regression bugs.
  * Unit or integration tests for complex, fragile, or important functionality.

```

And tests should always run without migrations (or at least, with only new migrations since `initial_data.sql` was last updated). In `commands.md` we say:

```
Run the tests:

    $ runtests.sh

Run a single test:

    $ runtests.sh path.to:TestCase.test_method

```
